name: Pull Request Quality Checklist

on:
  pull_request_target:
    types: [opened]

jobs:
  pr-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Post PR checklist
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🚀 Great work on the PR! Just one last quick thing to check before merge:\n👉 [Final checklist](https://www.youtube.com/watch?v=dQw4w9WgXcQ)"
            })
