name: Funny Jokes PRs
on:
  pull_request-target:
    types: [opened]

jobs:
  funny-jokes:
    runs-on: ubuntu-latest
    steps:
      - name: Comment a funny joke
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "👀 [Just a quick video before we begin](https://www.youtube.com/watch?v=dQw4w9WgXcQ)"
            })
